name: CD
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Configure NPM
      run: |
        npm config set @ultimicro:registry https://registry.npmjs.org/
        npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
    - name: Install dependencies
      run: npm install
    - name: Publish
      run: npm publish --access public
